export type ConfigName =
  "colors" |
  "theme" |
  "backgroundAttachment" |
  "backgroundClip" |
  "backgroundPosition" |
  "backgroundRepeat" |
  "backgroundSize" |
  "backgroundOrigin" |
  "backgroundImage" |
  "gradientDirection" |
  "gradient" |
  "strokeLineCap" |
  "strokeLineJoin" |
  "flexDirection" |
  "flexWrap" |
  "flexStretch" |
  "flexGrow" |
  "flexShrink" |
  "gridAutoColumns" |
  "gridAutoFlow" |
  "gridAutoRows" |
  "gridColumn" |
  "gridRow" |
  "gridColumnEnd" |
  "gridColumnStart" |
  "gridRowStart" |
  "gridRowEnd" |
  "gridTemplateColumns" |
  "gridTemplateRows" |
  "borderRadius" |
  "borderStyle" |
  "borderWidth" |
  "outlineOffset" |
  "ringOffset" |
  "blendMode" |
  "boxShadow" |
  "boxDecorationBreak" |
  "imageRendering" |
  "listStyleType" |
  "listStylePosition" |
  "overflow" |
  "overscroll" |
  "aspectRatio" |
  "blur" |
  "brightness" |
  "contrast" |
  "dropShadow" |
  "grayscale" |
  "hueRotate" |
  "invert" |
  "saturate" |
  "sepia" |
  "opacity" |
  "screens" |
  "orientations" |
  "motions" |
  "tShirtScale" |
  "width" |
  "height" |
  "spacing" |
  "spaceBetween" |
  "margin" |
  "padding" |
  "animation" |
  "animationDuration" |
  "animationDelay" |
  "animationIterationCount" |
  "animationTimingFunction" |
  "degree" |
  "rotate" |
  "scale" |
  "skew" |
  "translate" |
  "transformOrigin" |
  "transformStyle" |
  "perspective" |
  "perspectiveOrigin" |
  "justifyContent" |
  "justifyItems" |
  "justifySelf" |
  "alignContent" |
  "alignItems" |
  "alignSelf" |
  "placeContent" |
  "placeItems" |
  "placeSelf" |
  "inset" |
  "objectFit" |
  "position" |
  "objectPosition" |
  "zIndex" |
  "touchAction" |
  "userSelect" |
  "tableDisplay" |
  "transitionProperty" |
  "transitionDelay" |
  "transitionDuration" |
  "transitionTimingFunction" |
  "fontFamily" |
  "fontStyle" |
  "fontSize" |
  "fontWeight" |
  "hyphens" |
  "letterSpacing" |
  "lineHeight" |
  "tabSize" |
  "textAlign" |
  "verticalAlign" |
  "fontVariantNumeric" |
  "textDecorationType" |
  "textDecorationStyle" |
  "textDecorationThickness" |
  "textDecorationOffset" |
  "textIndent" |
  "textStrokeWidth" |
  "textShadow" |
  "textTransform" |
  "whiteSpace" |
  "writingMode" |
  "writingOrientation";

// TODO: define utilities type, we need use handler and style type, maybe move this to utilities or windijs ?
export function defineConfig<K extends ConfigName, T extends object | undefined> (config: (Record<K, T> | Record<string, T>) & { variants?: Record<string, string>, utilities?: Record<string, object> }) {
  return config;
}
