export const animationConfig = {
  none: "none",
  spin: "spin 1s linear infinite",
  ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
  pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  bounce: "bounce 1s infinite",
  shock: {
    animation: "shock",
    transformOrigin: "center bottom",
  },
  flash: "flash",
  bubble: "bubble",
  rubberBand: "rubberBand",
  shakeX: "shakeX",
  shakeY: "shakeY",
  headShake: "headShake 1s ease-in-out",
  swing: {
    animation: "swing",
    transformOrigin: "top center",
  },
  tada: "tada",
  wobble: "wobble",
  jello: "jello",
  heartBeat: "heartBeat 1s ease-in-out",
  hinge: "hinge 2s",
  jackIn: "jackInTheBox",
  lightSpeedInLeft: "lightSpeedInLeft",
  lightSpeedInRight: "lightSpeedInRight",
  lightSpeedOutLeft: "lightSpeedOutLeft",
  lightSpeedOutRight: "lightSpeedOutRight",
  flip: {
    animation: "flip",
    backfaceVisibility: "visible",
  },
  flipInX: {
    animation: "flipInX",
    backfaceVisibility: "visible",
  },
  flipInY: {
    animation: "flipInY",
    backfaceVisibility: "visible",
  },
  flipOutX: {
    animation: "flipOutX",
    backfaceVisibility: "visible",
  },
  flipOutY: {
    animation: "flipOutY",
    backfaceVisibility: "visible",
  },
  rotateIn: "rotateIn",
  rotateInDownLeft: "rotateInDownLeft",
  rotateInDownRight: "rotateInDownRight",
  rotateInUpLeft: "rotateInUpLeft",
  rotateInUpRight: "rotateInUpRight",
  rotateOut: "rotateOut",
  rotateOutDownLeft: "rotateOutDownLeft",
  rotateOutDownRight: "rotateOutDownRight",
  rotateOutUpLeft: "rotateOutUpLeft",
  rotateOutUpRight: "rotateOutUpRight",
  rollIn: "rollIn",
  rollOut: "rollOut",
  zoomIn: "zoomIn",
  zoomInDown: "zoomInDown",
  zoomInLeft: "zoomInLeft",
  zoomInRight: "zoomInRight",
  zoomInUp: "zoomInUp",
  bounceIn: "bounceIn 750ms",
  bounceInDown: "bounceInDown",
  bounceInLeft: "bounceInLeft",
  bounceInRight: "bounceInRight",
  bounceInUp: "bounceInUp",
  bounceOut: "bounceOut 750ms",
  bounceOutDown: "bounceOutDown",
  bounceOutLeft: "bounceOutLeft",
  bounceOutRight: "bounceOutRight",
  bounceOutUp: "bounceOutUp",
  zoomOut: "zoomOut",
  zoomOutDown: "zoomOutDown",
  zoomOutLeft: "zoomOutLeft",
  zoomOutRight: "zoomOutRight",
  zoomOutUp: "zoomOutUp",
  slideInDown: "slideInDown",
  slideInLeft: "slideInLeft",
  slideInRight: "slideInRight",
  slideInUp: "slideInUp",
  slideOutDown: "slideOutDown",
  slideOutLeft: "slideOutLeft",
  slideOutRight: "slideOutRight",
  slideOutUp: "slideOutUp",
  fadeIn: "fadeIn",
  fadeInDown: "fadeInDown",
  fadeInDownBig: "fadeInDownBig",
  fadeInLeft: "fadeInLeft",
  fadeInLeftBig: "fadeInLeftBig",
  fadeInRight: "fadeInRight",
  fadeInRightBig: "fadeInRightBig",
  fadeInUp: "fadeInUp",
  fadeInUpBig: "fadeInUpBig",
  fadeInTopLeft: "fadeInTopLeft",
  fadeInTopRight: "fadeInTopRight",
  fadeInBottomLeft: "fadeInBottomLeft",
  fadeInBottomRight: "fadeInBottomRight",
  fadeOut: "fadeOut",
  fadeOutDown: "fadeOutDown",
  fadeOutDownBig: "fadeOutDownBig",
  fadeOutLeft: "fadeOutLeft",
  fadeOutLeftBig: "fadeOutLeftBig",
  fadeOutRight: "fadeOutRight",
  fadeOutRightBig: "fadeOutRightBig",
  fadeOutUp: "fadeOutUp",
  fadeOutUpBig: "fadeOutUpBig",
  backInUp: "backInUp",
  backInDown: "backInDown",
  backInLeft: "backInLeft",
  backInRight: "backInRight",
  backOutUp: "backOutUp",
  backOutDown: "backOutDown",
  backOutLeft: "backOutLeft",
  backOutRight: "backOutRight",
};

export const animationDurationConfig = {
  DEFAULT: "1000ms",
  75: "75ms",
  100: "100ms",
  150: "150ms",
  200: "200ms",
  300: "300ms",
  500: "500ms",
  700: "700ms",
  1000: "1000ms",
  1500: "1500ms",
  2000: "2000ms",
  2500: "2500ms",
  3000: "3000ms",
};

export const animationDelayConfig = {
  DEFAULT: "500ms",
  75: "75ms",
  100: "100ms",
  150: "150ms",
  200: "200ms",
  300: "300ms",
  500: "500ms",
  700: "700ms",
  1000: "1000ms",
  1500: "1500ms",
  2000: "2000ms",
  2500: "2500ms",
  3000: "3000ms",
};

export const animationIterationCount = {
  DEFAULT: "1",
  loop: "infinite",
  "repeat-1": "1",
  "repeat-2": "2",
  "repeat-3": "3",
  "repeat-4": "4",
  "repeat-5": "5",
  "repeat-6": "6",
  "repeat-7": "7",
  "repeat-8": "8",
  "repeat-9": "9",
  "repeat-10": "10",
  "repeat-11": "11",
  "repeat-12": "12",
};

export const animationTimingFunction = {
  DEFAULT: "ease",
  linear: "linear",
  in: "ease-in",
  out: "ease-out",
  "in-out": "ease-in-out",
};
