# This workflow will do a clean install of node dependencies, build the source code and generate docs.

name: Docs

on:
  push:
    tags:
      - v*
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate docs
        run: pnpm docs:prod

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/.vitepress/dist
