# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
      
      - name: Set node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Lint code
        run: pnpm lint
        
      - name: Run tests
        run: pnpm test
